### ISSUE TITLE
Did you get the right answer according to the algorithm introduced by this paper?

### ISSUE THREAD

**Issue by wpkong** [Youlissize/polycube#1]
Coincidentally, I am also reproducing the code of this paper now, lol. And I used autograd to calculate the Jacobian matrix and Hessian matrix. But when I wrote code to solve the equation, I found the result delta X can not make the energy lower. So could you please tell me what about your results? Can the algorithm produce the right polycube or have you changed it? Thank you.😊

**Comment by Youlissize** [comment]
Hello,
currently we are only using l1-norme energy with ARAP control and the triangle surface constraint, we just do not use exactly the same formula for ARAP but I guess they doing the same thing. And it works, but we don't use anything for the Jacobian and Hessian, we compute it "manually"

**Comment by yjxkwp** [comment]
Dear Youlissize, 
Thank you very much for your answer! And I have completed the l1-norm with CppAD and IPopt, and it indeed works. However, the ARAP formula this paper introducing includes a polar decomposition operator but for some technologically reasons, it will invites many errors. So would you please tell me what ARAP method you took (may be a paper)? Thanks a lot again🤝

**Comment by wpkong** [comment]
Dear Youlissize,
Thank you very much for your answer! And I have completed the l1-norm with CppAD and IPopt, and it indeed works!
